### Introduction to NumPy

In [2]:
# Lists cannot be multiplied together.
list_a = [1, 2, 3]
list_b = [2, 4, 6]

list_a * list_b

TypeError: can't multiply sequence by non-int of type 'list'

In [4]:
# To perform element-wise multiplication between two lists, you could
# use a for loop.
list_c = []
for i in range(len(list_a)):
    list_c.append(list_a[i] * list_b[i])

list_c

[2, 8, 18]

In [5]:
# NumPy arrays let you perform array operations.

# Import numpy, aliased as np.
import numpy as np

# Convert lists to arrays.
array_a = np.array(list_a)
array_b = np.array(list_b)

# Perform element-wise multiplication between the arrays.
array_a * array_b

array([ 2,  8, 18])

In [6]:
import numpy as np

# The np.array() function converts an object to an ndarray
x = np.array([1, 2, 3, 4])
x

array([1, 2, 3, 4])

In [7]:
# Arrays can be indexed.
x[-1] = 5
x

array([1, 2, 3, 5])

In [8]:
# Trying to access an index that doesn't exist will throw an error.
x[4] = 10

IndexError: index 4 is out of bounds for axis 0 with size 4

In [9]:
# Arrays cast every element they contain as the same data type.
arr = np.array([1, 2, 'coconut'])
arr

array(['1', '2', 'coconut'], dtype='<U21')

In [10]:
# NumPy arrays are a class called `ndarray`.
print(type(arr))

<class 'numpy.ndarray'>


In [11]:
# The dtype attribute returns the data type of an array's contents.
arr = np.array([1, 2, 3])
arr.dtype

dtype('int64')

In [12]:
# The shape attribute returns the number of elements in each dimension
# of an array.
arr.shape

(3,)

In [13]:
# The ndim attribute returns the number of dimensions in an array.
arr.ndim

1

In [14]:
# Create a 2D array by passing a list of lists to np.array() function.
arr_2d = np.array([[1, 2], [3, 4], [5, 6], [7, 8]])
print(arr_2d.shape)
print(arr_2d.ndim)
arr_2d

(4, 2)
2


array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [15]:
# Create a 3D array by passing a list of two lists of lists to np.array() function.
arr_3d = np.array([[[1, 2, 3],
                   [3, 4, 5]],

                  [[5, 6, 7],
                   [7, 8, 9]]]
)

print(arr_3d.shape)
print(arr_3d.ndim)
arr_3d

(2, 2, 3)
3


array([[[1, 2, 3],
        [3, 4, 5]],

       [[5, 6, 7],
        [7, 8, 9]]])

In [16]:
# The reshape() method changes the shape of an array.
arr_2d = arr_2d.reshape(2, 4)
arr_2d

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [17]:
# Create new array
arr = np.array([1, 2, 3, 4, 5])

# The mean() method returns the mean of the elements in an array.
np.mean(arr)

np.float64(3.0)

In [18]:
# The log() method returns the natural logarithm of the elements in an array.
np.log(arr)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791])

In [19]:
# The floor() method returns the value of a number rounded down
# to the nearest integer.
np.floor(5.7)

np.float64(5.0)

In [20]:
# The ceil() method returns the value of a number rounded up
# to the nearest integer.
np.ceil(5.3)

np.float64(6.0)